# Generated by Django 5.2.8 on 2025-11-11 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('giro', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField()),
                ('mercado', models.CharField(max_length=10)),
                ('instrumento', models.CharField(max_length=100)),
                ('fecha_pago', models.DateField()),
                ('descripcion_dividendo', models.TextField(blank=True, null=True)),
                ('secuencia_evento', models.IntegerField()),
                ('acogido_isfut', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('CORREDOR', 'Corredor'), ('SISTEMA', 'Sistema'), ('CARGA_MASIVA', 'Carga Masiva')], max_length=50)),
                ('tipo_sociedad', models.CharField(blank=True, choices=[('A', 'Abierta'), ('C', 'Cerrada')], max_length=1, null=True)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_carga', models.CharField(choices=[('MONTOS', 'Montos'), ('FACTORES', 'Factores')], max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_error', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FactoresCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_8', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_9', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_10', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('calificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.calificaciontributaria')),
            ],
        ),
    ]
