# Generated by Django 5.2.8 on 2025-11-12 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_11',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_12',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_13',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_14',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_15',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_16',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_17',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_18',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_19',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_20',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_21',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_22',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_23',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_24',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_25',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_26',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_27',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_28',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_29',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_30',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_31',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_32',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_33',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_34',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_35',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_36',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='factorescalificacion',
            name='factor_37',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPRESA', 'Usuario Empresa'), ('CONSULTA', 'Usuario Consulta')], default='EMPRESA', max_length=20)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calificaciones.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
