# Generated by Django 5.2.8 on 2025-11-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_factorescalificacion_factor_11_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
