# Generated by Django 5.2.8 on 2025-11-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_profile_empresa_profile_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario Normal'), ('VIEWER', 'Solo Lectura')], default='USER', max_length=10),
        ),
    ]
