# Generated by Django 5.2.8 on 2025-11-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0006_profile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_email_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mfa_email_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
